import type { Prompt } from "./types";

export const PROMPTS: Prompt[] = [
  { id: "p01", text: "The worst thing to hear from a pilot right before takeoff" },
  { id: "p02", text: "A terrible name for a fancy restaurant" },
  { id: "p03", text: "The rejected slogan for a gym that never opened" },
  { id: "p04", text: "Something a haunted fridge would whisper at night" },
  { id: "p05", text: "The title of a documentary about your group chat" },
  { id: "p06", text: "The least inspiring fortune cookie message" },
  { id: "p07", text: "A warning label that should be on every office chair" },
  { id: "p08", text: "What a villain says after running out of dramatic plans" },
  { id: "p09", text: "The most suspicious thing to find in a birthday cake" },
  { id: "p10", text: "A bad password hint for someone named Alex" },
  { id: "p11", text: "A phrase nobody wants to hear from their dentist" },
  { id: "p12", text: "The secret menu item at the world's saddest cafe" },
  { id: "p13", text: "The name of a perfume no one asked for" },
  { id: "p14", text: "A text message that would ruin a wedding toast" },
  { id: "p15", text: "The final boss of doing laundry" },
  { id: "p16", text: "A rejected theme for a children's birthday party" },
  { id: "p17", text: "What the moon would complain about if it could talk" },
  { id: "p18", text: "A terrible app idea that somehow got funded" },
  { id: "p19", text: "The worst name for a motivational podcast" },
  { id: "p20", text: "A sentence that should never start a work email" },
  { id: "p21", text: "A weird thing to shout before jumping into a pool" },
  { id: "p22", text: "The fake class every school should offer" },
  { id: "p23", text: "What a toaster dreams about" },
  { id: "p24", text: "The worst prize to win on live TV" },
  { id: "p25", text: "A suspicious excuse for being late" },
  { id: "p26", text: "The name of a very dramatic sandwich" },
  { id: "p27", text: "The first rule of a club nobody wants to join" },
  { id: "p28", text: "A thing you should never say during a magic trick" },
  { id: "p29", text: "An award category invented just for your friend group" },
  { id: "p30", text: "The worst possible museum exhibit" }
];
